services:
  postgres:
    container_name: "devboard-db"
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - devboard-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    restart: unless-stopped


  backend:
    container_name: "devboard-backend"
    image: palashhh18/devboard-backend:${IMAGE_TAG:-latest}
    environment:
      PORT: "${BACKEND_PORT}"
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_PORT}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${BACKEND_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    container_name: "devboard-frontend"
    image: palashhh18/devboard-frontend:${IMAGE_TAG:-latest}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_HOST_PORT}:4173"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4173"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  devboard-data:
