apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devboard-cluster
  region: ap-south-1
iam:
  withOIDC: true

managedNodeGroups:
  - name: devboard-nodes
    instanceType: c7i-flex.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20   
    ssh:
      enableSsm: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
  - name: metrics-server
