apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devboard
  name: devboard-operator-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "services", "pods", "pods/log"]
  verbs: ["get", "list", "watch","delete"]
