name: DevSecOps

on:
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml
        secrets: inherit

    secret-scanning:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
        secrets: inherit

    code-testing:
        uses: ./.github/workflows/code-testing.yml
        secrets: inherit

    docker-scans:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit

    sonarqube-scan:
        uses: ./.github/workflows/sonarqube-scan.yml
        secrets: inherit

    docker-build-and-push:
        uses: ./.github/workflows/docker.yml
        needs: [code-quality,secret-scanning,dependency-scan,code-testing,docker-scans,sonarqube-scan]
        secrets: inherit

    deployment:
        needs: [docker-build-and-push]
        uses: ./.github/workflows/deployment.yml
        secrets: inherit

    dast-scan:
        needs: [deployment]
        uses: ./.github/workflows/dast-scan.yml
        secrets: inherit
